### ISSUE TITLE
USER STORY: Anonymous user feedback

### ISSUE THREAD

**Issue by Maximiliane-K** [Maximiliane-K/My-First-Agile-Project#5]
In order to **get feedback from the user** as a **administrator**, I can **post a poll*

## Acceptance Criteria 
* The option should be provided with a text field for the question
* Under the text field there is a plus sign to add answer options 

## Tasks
- [ ] Create HTML and CSS for question and answer option 
- [ ] Create the controller function 
- [ ] Test the functionality
